SELECT DISTINCT  CITY
FROM STATION
WHERE UPPER(SUBSTRING(CITY FROM LENGTH(CITY) FOR 1)) NOT IN ('a', 'e', 'i', 'o', 'u')
AND UPPER(SUBSTRING(CITY FROM 1 FOR 1)) NOT IN ('a', 'e', 'i', 'o', 'u');   